import type { LogicNode } from './types';

export function generateESPHomeFirmware(esp32Nodes: LogicNode[]): string {
  const buttons = esp32Nodes.filter(n => n.templateId === 'esp32-button' || n.templateId === 'esp32-toggle');
  const pots = esp32Nodes.filter(n => n.templateId === 'esp32-pot');
  const encoders = esp32Nodes.filter(n => n.templateId === 'esp32-encoder');
  const leds = esp32Nodes.filter(n => n.templateId === 'esp32-led');

  let yaml = `# SFLC ESP32 GPIO Controller
# Auto-generated by STOKIO FX Light Controller
# Flash via ESPHome Dashboard

esphome:
  name: sflc-gpio-controller
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  password: !secret api_password

ota:
  password: !secret ota_password

logger:

# MQTT for SFLC communication
mqtt:
  broker: !secret mqtt_broker
  topic_prefix: sflc/gpio
`;

  if (buttons.length > 0) {
    yaml += `\n# ── Buttons & Switches ──\nbinary_sensor:\n`;
    buttons.forEach(n => {
      const pin = n.config.gpioPin ?? 4;
      const name = n.name.toLowerCase().replace(/\s+/g, '_');
      yaml += `  - platform: gpio
    name: "${n.name}"
    pin:
      number: ${pin}
      mode: INPUT_PULLUP
      inverted: true
    filters:\n`;
      if (n.config.buttonMode === 'toggle') {
        yaml += `      - delayed_on: 50ms
      - delayed_off: 50ms
    on_press:
      - mqtt.publish:
          topic: sflc/gpio/${name}/state
          payload: "ON"
    on_release:
      - mqtt.publish:
          topic: sflc/gpio/${name}/state
          payload: "OFF"
`;
      } else if (n.config.buttonMode === 'hold') {
        yaml += `      - delayed_on: 50ms
    on_press:
      - mqtt.publish:
          topic: sflc/gpio/${name}/pressed
          payload: "1"
    on_release:
      - mqtt.publish:
          topic: sflc/gpio/${name}/released
          payload: "1"
    on_click:
      min_length: ${n.config.holdTime || 1000}ms
      then:
        - mqtt.publish:
            topic: sflc/gpio/${name}/hold
            payload: "1"
`;
      } else if (n.config.buttonMode === 'double-press') {
        yaml += `      - delayed_on: 50ms
    on_multi_click:
      - timing:
          - ON for at most ${n.config.doublePressTime || 300}ms
          - OFF for at most ${n.config.doublePressTime || 300}ms
          - ON for at most ${n.config.doublePressTime || 300}ms
          - OFF for at least 200ms
        then:
          - mqtt.publish:
              topic: sflc/gpio/${name}/double
              payload: "1"
      - timing:
          - ON for at most 500ms
          - OFF for at least 500ms
        then:
          - mqtt.publish:
              topic: sflc/gpio/${name}/single
              payload: "1"
`;
      } else {
        yaml += `      - delayed_on: 50ms
    on_press:
      - mqtt.publish:
          topic: sflc/gpio/${name}/pressed
          payload: "1"
    on_release:
      - mqtt.publish:
          topic: sflc/gpio/${name}/released
          payload: "1"
`;
      }
    });
  }

  if (pots.length > 0) {
    yaml += `\n# ── Analog Inputs (Potentiometers) ──\nsensor:\n`;
    pots.forEach(n => {
      const pin = n.config.gpioPin ?? 34;
      const name = n.name.toLowerCase().replace(/\s+/g, '_');
      yaml += `  - platform: adc
    name: "${n.name}"
    pin: ${pin}
    attenuation: 11db
    update_interval: 100ms
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 3
      - lambda: |-
          return (x * ${n.config.potMax ?? 255}) / 3.3;
    on_value:
      - mqtt.publish:
          topic: sflc/gpio/${name}/value
          payload: !lambda 'return to_string((int)x);'
`;
    });
  }

  if (encoders.length > 0) {
    yaml += `\n# ── Rotary Encoders ──\nsensor:\n`;
    encoders.forEach(n => {
      const pin = n.config.gpioPin ?? 16;
      const name = n.name.toLowerCase().replace(/\s+/g, '_');
      yaml += `  - platform: rotary_encoder
    name: "${n.name}"
    pin_a: ${pin}
    pin_b: ${pin + 1}
    on_value:
      - mqtt.publish:
          topic: sflc/gpio/${name}/value
          payload: !lambda 'return to_string((int)x);'
`;
    });
  }

  if (leds.length > 0) {
    yaml += `\n# ── LED Outputs ──\noutput:\n`;
    leds.forEach(n => {
      const pin = n.config.gpioPin ?? 2;
      const name = n.name.toLowerCase().replace(/\s+/g, '_');
      yaml += `  - platform: ledc
    pin: ${pin}
    id: ${name}_pwm

light:
  - platform: monochromatic
    name: "${n.name}"
    output: ${name}_pwm
`;
    });
  }

  return yaml;
}

export function generateWLEDUsermod(esp32Nodes: LogicNode[]): string {
  const buttons = esp32Nodes.filter(n => n.templateId === 'esp32-button' || n.templateId === 'esp32-toggle');
  const pots = esp32Nodes.filter(n => n.templateId === 'esp32-pot');

  let code = `#pragma once
// SFLC GPIO Usermod for WLED
// Auto-generated by STOKIO FX Light Controller
// Place this file in wled00/usermods/sflc_gpio/

#include "wled.h"

class SFLCGpioUsermod : public Usermod {
  private:
`;

  // Pin definitions
  buttons.forEach(n => {
    code += `    static const uint8_t PIN_${n.name.toUpperCase().replace(/\s+/g, '_')} = ${n.config.gpioPin ?? 4};\n`;
  });
  pots.forEach(n => {
    code += `    static const uint8_t PIN_${n.name.toUpperCase().replace(/\s+/g, '_')} = ${n.config.gpioPin ?? 34};\n`;
  });

  code += `
    // Button state tracking
`;
  buttons.forEach((n, i) => {
    code += `    bool lastState_${i} = HIGH;\n`;
    code += `    unsigned long lastPress_${i} = 0;\n`;
    if (n.config.buttonMode === 'double-press') {
      code += `    uint8_t clickCount_${i} = 0;\n`;
    }
    if (n.config.buttonMode === 'hold') {
      code += `    bool holding_${i} = false;\n`;
    }
  });

  pots.forEach((_, i) => {
    code += `    int lastPotValue_${i} = -1;\n`;
  });

  code += `
  public:
    void setup() {
`;
  buttons.forEach(n => {
    code += `      pinMode(PIN_${n.name.toUpperCase().replace(/\s+/g, '_')}, INPUT_PULLUP);\n`;
  });
  code += `    }

    void loop() {
      unsigned long now = millis();
`;

  buttons.forEach((n, i) => {
    const pinName = `PIN_${n.name.toUpperCase().replace(/\s+/g, '_')}`;
    code += `
      // ${n.name}
      {
        bool state = digitalRead(${pinName});
        if (state != lastState_${i}) {
          lastState_${i} = state;
          if (state == LOW) { // pressed
            lastPress_${i} = now;
`;
    if (n.config.buttonMode === 'push-release') {
      code += `            // Send press via MQTT/UDP
            sendSFLCEvent("${n.name.toLowerCase().replace(/\s+/g, '_')}", "pressed");
`;
    } else if (n.config.buttonMode === 'toggle') {
      code += `            toggleOnOff();
            sendSFLCEvent("${n.name.toLowerCase().replace(/\s+/g, '_')}", bri > 0 ? "on" : "off");
`;
    } else if (n.config.buttonMode === 'double-press') {
      code += `            clickCount_${i}++;
            if (clickCount_${i} >= 2) {
              sendSFLCEvent("${n.name.toLowerCase().replace(/\s+/g, '_')}", "double");
              clickCount_${i} = 0;
            }
`;
    }
    code += `          } else { // released
`;
    if (n.config.buttonMode === 'push-release') {
      code += `            sendSFLCEvent("${n.name.toLowerCase().replace(/\s+/g, '_')}", "released");
`;
    }
    if (n.config.buttonMode === 'hold') {
      code += `            if (holding_${i}) {
              holding_${i} = false;
              sendSFLCEvent("${n.name.toLowerCase().replace(/\s+/g, '_')}", "hold_release");
            }
`;
    }
    code += `          }
        }
`;
    if (n.config.buttonMode === 'hold') {
      code += `        if (state == LOW && !holding_${i} && (now - lastPress_${i} > ${n.config.holdTime || 1000})) {
          holding_${i} = true;
          sendSFLCEvent("${n.name.toLowerCase().replace(/\s+/g, '_')}", "hold");
        }
`;
    }
    if (n.config.buttonMode === 'double-press') {
      code += `        if (clickCount_${i} > 0 && (now - lastPress_${i} > ${n.config.doublePressTime || 300})) {
          if (clickCount_${i} == 1) sendSFLCEvent("${n.name.toLowerCase().replace(/\s+/g, '_')}", "single");
          clickCount_${i} = 0;
        }
`;
    }
    code += `      }\n`;
  });

  pots.forEach((n, i) => {
    const pinName = `PIN_${n.name.toUpperCase().replace(/\s+/g, '_')}`;
    code += `
      // ${n.name} (Analog)
      {
        int raw = analogRead(${pinName});
        int mapped = map(raw, 0, 4095, ${n.config.potMin ?? 0}, ${n.config.potMax ?? 255});
        if (abs(mapped - lastPotValue_${i}) > 2) {
          lastPotValue_${i} = mapped;
          sendSFLCValue("${n.name.toLowerCase().replace(/\s+/g, '_')}", mapped);
        }
      }
`;
  });

  code += `    }

    void sendSFLCEvent(const char* name, const char* event) {
      // Send via MQTT if configured
      #ifdef WLED_ENABLE_MQTT
      char topic[80];
      snprintf(topic, sizeof(topic), "sflc/gpio/%s/%s", name, event);
      mqtt->publish(topic, 0, false, "1");
      #endif
    }

    void sendSFLCValue(const char* name, int value) {
      #ifdef WLED_ENABLE_MQTT
      char topic[80], payload[8];
      snprintf(topic, sizeof(topic), "sflc/gpio/%s/value", name);
      snprintf(payload, sizeof(payload), "%d", value);
      mqtt->publish(topic, 0, false, payload);
      #endif
    }

    uint16_t getId() { return USERMOD_ID_EXAMPLE; }
};
`;

  return code;
}
